/*
 * Copyright 2015 - 2016 Red Bull Media House GmbH <http://www.redbullmediahouse.com> - all rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DurableEventFormats.proto

package com.rbmhtechnology.eventuate.serializer;

public final class DurableEventFormats {
  private DurableEventFormats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DurableEventFormatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DurableEventFormat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .PayloadFormat payload = 1;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional .PayloadFormat payload = 1;</code>
     */
    com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat getPayload();
    /**
     * <code>optional .PayloadFormat payload = 1;</code>
     */
    com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder getPayloadOrBuilder();

    /**
     * <code>optional string emitterId = 2;</code>
     */
    boolean hasEmitterId();
    /**
     * <code>optional string emitterId = 2;</code>
     */
    java.lang.String getEmitterId();
    /**
     * <code>optional string emitterId = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmitterIdBytes();

    /**
     * <code>optional string emitterAggregateId = 3;</code>
     */
    boolean hasEmitterAggregateId();
    /**
     * <code>optional string emitterAggregateId = 3;</code>
     */
    java.lang.String getEmitterAggregateId();
    /**
     * <code>optional string emitterAggregateId = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmitterAggregateIdBytes();

    /**
     * <code>repeated string customDestinationAggregateIds = 4;</code>
     */
    java.util.List<java.lang.String>
        getCustomDestinationAggregateIdsList();
    /**
     * <code>repeated string customDestinationAggregateIds = 4;</code>
     */
    int getCustomDestinationAggregateIdsCount();
    /**
     * <code>repeated string customDestinationAggregateIds = 4;</code>
     */
    java.lang.String getCustomDestinationAggregateIds(int index);
    /**
     * <code>repeated string customDestinationAggregateIds = 4;</code>
     */
    com.google.protobuf.ByteString
        getCustomDestinationAggregateIdsBytes(int index);

    /**
     * <code>optional int64 systemTimestamp = 5;</code>
     */
    boolean hasSystemTimestamp();
    /**
     * <code>optional int64 systemTimestamp = 5;</code>
     */
    long getSystemTimestamp();

    /**
     * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
     */
    boolean hasVectorTimestamp();
    /**
     * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
     */
    com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat getVectorTimestamp();
    /**
     * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
     */
    com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormatOrBuilder getVectorTimestampOrBuilder();

    /**
     * <code>optional string processId = 7;</code>
     */
    boolean hasProcessId();
    /**
     * <code>optional string processId = 7;</code>
     */
    java.lang.String getProcessId();
    /**
     * <code>optional string processId = 7;</code>
     */
    com.google.protobuf.ByteString
        getProcessIdBytes();

    /**
     * <code>optional string localLogId = 8;</code>
     */
    boolean hasLocalLogId();
    /**
     * <code>optional string localLogId = 8;</code>
     */
    java.lang.String getLocalLogId();
    /**
     * <code>optional string localLogId = 8;</code>
     */
    com.google.protobuf.ByteString
        getLocalLogIdBytes();

    /**
     * <code>optional int64 localSequenceNr = 9;</code>
     */
    boolean hasLocalSequenceNr();
    /**
     * <code>optional int64 localSequenceNr = 9;</code>
     */
    long getLocalSequenceNr();

    /**
     * <code>optional int64 persistOnEventSequenceNr = 10;</code>
     */
    boolean hasPersistOnEventSequenceNr();
    /**
     * <code>optional int64 persistOnEventSequenceNr = 10;</code>
     */
    long getPersistOnEventSequenceNr();

    /**
     * <code>optional string deliveryId = 11;</code>
     */
    boolean hasDeliveryId();
    /**
     * <code>optional string deliveryId = 11;</code>
     */
    java.lang.String getDeliveryId();
    /**
     * <code>optional string deliveryId = 11;</code>
     */
    com.google.protobuf.ByteString
        getDeliveryIdBytes();
  }
  /**
   * Protobuf type {@code DurableEventFormat}
   */
  public  static final class DurableEventFormat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DurableEventFormat)
      DurableEventFormatOrBuilder {
    // Use DurableEventFormat.newBuilder() to construct.
    private DurableEventFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DurableEventFormat() {
      emitterId_ = "";
      emitterAggregateId_ = "";
      customDestinationAggregateIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      systemTimestamp_ = 0L;
      processId_ = "";
      localLogId_ = "";
      localSequenceNr_ = 0L;
      persistOnEventSequenceNr_ = 0L;
      deliveryId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DurableEventFormat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = payload_.toBuilder();
              }
              payload_ = input.readMessage(com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payload_);
                payload_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              emitterId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              emitterAggregateId_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                customDestinationAggregateIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              customDestinationAggregateIds_.add(bs);
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              systemTimestamp_ = input.readInt64();
              break;
            }
            case 50: {
              com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = vectorTimestamp_.toBuilder();
              }
              vectorTimestamp_ = input.readMessage(com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vectorTimestamp_);
                vectorTimestamp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              processId_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              localLogId_ = bs;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              localSequenceNr_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000100;
              persistOnEventSequenceNr_ = input.readInt64();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              deliveryId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          customDestinationAggregateIds_ = customDestinationAggregateIds_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rbmhtechnology.eventuate.serializer.DurableEventFormats.internal_static_DurableEventFormat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rbmhtechnology.eventuate.serializer.DurableEventFormats.internal_static_DurableEventFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat.class, com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat.Builder.class);
    }

    private int bitField0_;
    public static final int PAYLOAD_FIELD_NUMBER = 1;
    private com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat payload_;
    /**
     * <code>optional .PayloadFormat payload = 1;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .PayloadFormat payload = 1;</code>
     */
    public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat getPayload() {
      return payload_ == null ? com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.getDefaultInstance() : payload_;
    }
    /**
     * <code>optional .PayloadFormat payload = 1;</code>
     */
    public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder getPayloadOrBuilder() {
      return payload_ == null ? com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.getDefaultInstance() : payload_;
    }

    public static final int EMITTERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object emitterId_;
    /**
     * <code>optional string emitterId = 2;</code>
     */
    public boolean hasEmitterId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string emitterId = 2;</code>
     */
    public java.lang.String getEmitterId() {
      java.lang.Object ref = emitterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          emitterId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string emitterId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmitterIdBytes() {
      java.lang.Object ref = emitterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emitterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMITTERAGGREGATEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object emitterAggregateId_;
    /**
     * <code>optional string emitterAggregateId = 3;</code>
     */
    public boolean hasEmitterAggregateId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string emitterAggregateId = 3;</code>
     */
    public java.lang.String getEmitterAggregateId() {
      java.lang.Object ref = emitterAggregateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          emitterAggregateId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string emitterAggregateId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmitterAggregateIdBytes() {
      java.lang.Object ref = emitterAggregateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emitterAggregateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMDESTINATIONAGGREGATEIDS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList customDestinationAggregateIds_;
    /**
     * <code>repeated string customDestinationAggregateIds = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCustomDestinationAggregateIdsList() {
      return customDestinationAggregateIds_;
    }
    /**
     * <code>repeated string customDestinationAggregateIds = 4;</code>
     */
    public int getCustomDestinationAggregateIdsCount() {
      return customDestinationAggregateIds_.size();
    }
    /**
     * <code>repeated string customDestinationAggregateIds = 4;</code>
     */
    public java.lang.String getCustomDestinationAggregateIds(int index) {
      return customDestinationAggregateIds_.get(index);
    }
    /**
     * <code>repeated string customDestinationAggregateIds = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCustomDestinationAggregateIdsBytes(int index) {
      return customDestinationAggregateIds_.getByteString(index);
    }

    public static final int SYSTEMTIMESTAMP_FIELD_NUMBER = 5;
    private long systemTimestamp_;
    /**
     * <code>optional int64 systemTimestamp = 5;</code>
     */
    public boolean hasSystemTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 systemTimestamp = 5;</code>
     */
    public long getSystemTimestamp() {
      return systemTimestamp_;
    }

    public static final int VECTORTIMESTAMP_FIELD_NUMBER = 6;
    private com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat vectorTimestamp_;
    /**
     * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
     */
    public boolean hasVectorTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
     */
    public com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat getVectorTimestamp() {
      return vectorTimestamp_ == null ? com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.getDefaultInstance() : vectorTimestamp_;
    }
    /**
     * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
     */
    public com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormatOrBuilder getVectorTimestampOrBuilder() {
      return vectorTimestamp_ == null ? com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.getDefaultInstance() : vectorTimestamp_;
    }

    public static final int PROCESSID_FIELD_NUMBER = 7;
    private volatile java.lang.Object processId_;
    /**
     * <code>optional string processId = 7;</code>
     */
    public boolean hasProcessId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string processId = 7;</code>
     */
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          processId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string processId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALLOGID_FIELD_NUMBER = 8;
    private volatile java.lang.Object localLogId_;
    /**
     * <code>optional string localLogId = 8;</code>
     */
    public boolean hasLocalLogId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string localLogId = 8;</code>
     */
    public java.lang.String getLocalLogId() {
      java.lang.Object ref = localLogId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localLogId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string localLogId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getLocalLogIdBytes() {
      java.lang.Object ref = localLogId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localLogId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALSEQUENCENR_FIELD_NUMBER = 9;
    private long localSequenceNr_;
    /**
     * <code>optional int64 localSequenceNr = 9;</code>
     */
    public boolean hasLocalSequenceNr() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 localSequenceNr = 9;</code>
     */
    public long getLocalSequenceNr() {
      return localSequenceNr_;
    }

    public static final int PERSISTONEVENTSEQUENCENR_FIELD_NUMBER = 10;
    private long persistOnEventSequenceNr_;
    /**
     * <code>optional int64 persistOnEventSequenceNr = 10;</code>
     */
    public boolean hasPersistOnEventSequenceNr() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 persistOnEventSequenceNr = 10;</code>
     */
    public long getPersistOnEventSequenceNr() {
      return persistOnEventSequenceNr_;
    }

    public static final int DELIVERYID_FIELD_NUMBER = 11;
    private volatile java.lang.Object deliveryId_;
    /**
     * <code>optional string deliveryId = 11;</code>
     */
    public boolean hasDeliveryId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string deliveryId = 11;</code>
     */
    public java.lang.String getDeliveryId() {
      java.lang.Object ref = deliveryId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deliveryId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deliveryId = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDeliveryIdBytes() {
      java.lang.Object ref = deliveryId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deliveryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasVectorTimestamp()) {
        if (!getVectorTimestamp().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getPayload());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, emitterId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, emitterAggregateId_);
      }
      for (int i = 0; i < customDestinationAggregateIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, customDestinationAggregateIds_.getRaw(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(5, systemTimestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(6, getVectorTimestamp());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, processId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, localLogId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(9, localSequenceNr_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(10, persistOnEventSequenceNr_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, deliveryId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPayload());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, emitterId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, emitterAggregateId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < customDestinationAggregateIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(customDestinationAggregateIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCustomDestinationAggregateIdsList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, systemTimestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getVectorTimestamp());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, processId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, localLogId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, localSequenceNr_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, persistOnEventSequenceNr_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, deliveryId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat)) {
        return super.equals(obj);
      }
      com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat other = (com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat) obj;

      boolean result = true;
      result = result && (hasPayload() == other.hasPayload());
      if (hasPayload()) {
        result = result && getPayload()
            .equals(other.getPayload());
      }
      result = result && (hasEmitterId() == other.hasEmitterId());
      if (hasEmitterId()) {
        result = result && getEmitterId()
            .equals(other.getEmitterId());
      }
      result = result && (hasEmitterAggregateId() == other.hasEmitterAggregateId());
      if (hasEmitterAggregateId()) {
        result = result && getEmitterAggregateId()
            .equals(other.getEmitterAggregateId());
      }
      result = result && getCustomDestinationAggregateIdsList()
          .equals(other.getCustomDestinationAggregateIdsList());
      result = result && (hasSystemTimestamp() == other.hasSystemTimestamp());
      if (hasSystemTimestamp()) {
        result = result && (getSystemTimestamp()
            == other.getSystemTimestamp());
      }
      result = result && (hasVectorTimestamp() == other.hasVectorTimestamp());
      if (hasVectorTimestamp()) {
        result = result && getVectorTimestamp()
            .equals(other.getVectorTimestamp());
      }
      result = result && (hasProcessId() == other.hasProcessId());
      if (hasProcessId()) {
        result = result && getProcessId()
            .equals(other.getProcessId());
      }
      result = result && (hasLocalLogId() == other.hasLocalLogId());
      if (hasLocalLogId()) {
        result = result && getLocalLogId()
            .equals(other.getLocalLogId());
      }
      result = result && (hasLocalSequenceNr() == other.hasLocalSequenceNr());
      if (hasLocalSequenceNr()) {
        result = result && (getLocalSequenceNr()
            == other.getLocalSequenceNr());
      }
      result = result && (hasPersistOnEventSequenceNr() == other.hasPersistOnEventSequenceNr());
      if (hasPersistOnEventSequenceNr()) {
        result = result && (getPersistOnEventSequenceNr()
            == other.getPersistOnEventSequenceNr());
      }
      result = result && (hasDeliveryId() == other.hasDeliveryId());
      if (hasDeliveryId()) {
        result = result && getDeliveryId()
            .equals(other.getDeliveryId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      if (hasEmitterId()) {
        hash = (37 * hash) + EMITTERID_FIELD_NUMBER;
        hash = (53 * hash) + getEmitterId().hashCode();
      }
      if (hasEmitterAggregateId()) {
        hash = (37 * hash) + EMITTERAGGREGATEID_FIELD_NUMBER;
        hash = (53 * hash) + getEmitterAggregateId().hashCode();
      }
      if (getCustomDestinationAggregateIdsCount() > 0) {
        hash = (37 * hash) + CUSTOMDESTINATIONAGGREGATEIDS_FIELD_NUMBER;
        hash = (53 * hash) + getCustomDestinationAggregateIdsList().hashCode();
      }
      if (hasSystemTimestamp()) {
        hash = (37 * hash) + SYSTEMTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSystemTimestamp());
      }
      if (hasVectorTimestamp()) {
        hash = (37 * hash) + VECTORTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getVectorTimestamp().hashCode();
      }
      if (hasProcessId()) {
        hash = (37 * hash) + PROCESSID_FIELD_NUMBER;
        hash = (53 * hash) + getProcessId().hashCode();
      }
      if (hasLocalLogId()) {
        hash = (37 * hash) + LOCALLOGID_FIELD_NUMBER;
        hash = (53 * hash) + getLocalLogId().hashCode();
      }
      if (hasLocalSequenceNr()) {
        hash = (37 * hash) + LOCALSEQUENCENR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLocalSequenceNr());
      }
      if (hasPersistOnEventSequenceNr()) {
        hash = (37 * hash) + PERSISTONEVENTSEQUENCENR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPersistOnEventSequenceNr());
      }
      if (hasDeliveryId()) {
        hash = (37 * hash) + DELIVERYID_FIELD_NUMBER;
        hash = (53 * hash) + getDeliveryId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DurableEventFormat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DurableEventFormat)
        com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rbmhtechnology.eventuate.serializer.DurableEventFormats.internal_static_DurableEventFormat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rbmhtechnology.eventuate.serializer.DurableEventFormats.internal_static_DurableEventFormat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat.class, com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat.Builder.class);
      }

      // Construct using com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPayloadFieldBuilder();
          getVectorTimestampFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (payloadBuilder_ == null) {
          payload_ = null;
        } else {
          payloadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        emitterId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        emitterAggregateId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        customDestinationAggregateIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        systemTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (vectorTimestampBuilder_ == null) {
          vectorTimestamp_ = null;
        } else {
          vectorTimestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        processId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        localLogId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        localSequenceNr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        persistOnEventSequenceNr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        deliveryId_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rbmhtechnology.eventuate.serializer.DurableEventFormats.internal_static_DurableEventFormat_descriptor;
      }

      public com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat getDefaultInstanceForType() {
        return com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat.getDefaultInstance();
      }

      public com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat build() {
        com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat buildPartial() {
        com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat result = new com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (payloadBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = payloadBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.emitterId_ = emitterId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.emitterAggregateId_ = emitterAggregateId_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          customDestinationAggregateIds_ = customDestinationAggregateIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.customDestinationAggregateIds_ = customDestinationAggregateIds_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.systemTimestamp_ = systemTimestamp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        if (vectorTimestampBuilder_ == null) {
          result.vectorTimestamp_ = vectorTimestamp_;
        } else {
          result.vectorTimestamp_ = vectorTimestampBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.processId_ = processId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.localLogId_ = localLogId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.localSequenceNr_ = localSequenceNr_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.persistOnEventSequenceNr_ = persistOnEventSequenceNr_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.deliveryId_ = deliveryId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat) {
          return mergeFrom((com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat other) {
        if (other == com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat.getDefaultInstance()) return this;
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        if (other.hasEmitterId()) {
          bitField0_ |= 0x00000002;
          emitterId_ = other.emitterId_;
          onChanged();
        }
        if (other.hasEmitterAggregateId()) {
          bitField0_ |= 0x00000004;
          emitterAggregateId_ = other.emitterAggregateId_;
          onChanged();
        }
        if (!other.customDestinationAggregateIds_.isEmpty()) {
          if (customDestinationAggregateIds_.isEmpty()) {
            customDestinationAggregateIds_ = other.customDestinationAggregateIds_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCustomDestinationAggregateIdsIsMutable();
            customDestinationAggregateIds_.addAll(other.customDestinationAggregateIds_);
          }
          onChanged();
        }
        if (other.hasSystemTimestamp()) {
          setSystemTimestamp(other.getSystemTimestamp());
        }
        if (other.hasVectorTimestamp()) {
          mergeVectorTimestamp(other.getVectorTimestamp());
        }
        if (other.hasProcessId()) {
          bitField0_ |= 0x00000040;
          processId_ = other.processId_;
          onChanged();
        }
        if (other.hasLocalLogId()) {
          bitField0_ |= 0x00000080;
          localLogId_ = other.localLogId_;
          onChanged();
        }
        if (other.hasLocalSequenceNr()) {
          setLocalSequenceNr(other.getLocalSequenceNr());
        }
        if (other.hasPersistOnEventSequenceNr()) {
          setPersistOnEventSequenceNr(other.getPersistOnEventSequenceNr());
        }
        if (other.hasDeliveryId()) {
          bitField0_ |= 0x00000400;
          deliveryId_ = other.deliveryId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasVectorTimestamp()) {
          if (!getVectorTimestamp().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat payload_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder> payloadBuilder_;
      /**
       * <code>optional .PayloadFormat payload = 1;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .PayloadFormat payload = 1;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat getPayload() {
        if (payloadBuilder_ == null) {
          return payload_ == null ? com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.getDefaultInstance() : payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PayloadFormat payload = 1;</code>
       */
      public Builder setPayload(com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          payloadBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PayloadFormat payload = 1;</code>
       */
      public Builder setPayload(
          com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PayloadFormat payload = 1;</code>
       */
      public Builder mergePayload(com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat value) {
        if (payloadBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              payload_ != null &&
              payload_ != com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.getDefaultInstance()) {
            payload_ =
              com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.newBuilder(payload_).mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          payloadBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PayloadFormat payload = 1;</code>
       */
      public Builder clearPayload() {
        if (payloadBuilder_ == null) {
          payload_ = null;
          onChanged();
        } else {
          payloadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .PayloadFormat payload = 1;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder getPayloadBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PayloadFormat payload = 1;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_ == null ?
              com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.getDefaultInstance() : payload_;
        }
      }
      /**
       * <code>optional .PayloadFormat payload = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder> 
          getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder>(
                  getPayload(),
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }

      private java.lang.Object emitterId_ = "";
      /**
       * <code>optional string emitterId = 2;</code>
       */
      public boolean hasEmitterId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string emitterId = 2;</code>
       */
      public java.lang.String getEmitterId() {
        java.lang.Object ref = emitterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            emitterId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string emitterId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmitterIdBytes() {
        java.lang.Object ref = emitterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emitterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string emitterId = 2;</code>
       */
      public Builder setEmitterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        emitterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string emitterId = 2;</code>
       */
      public Builder clearEmitterId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        emitterId_ = getDefaultInstance().getEmitterId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string emitterId = 2;</code>
       */
      public Builder setEmitterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        emitterId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object emitterAggregateId_ = "";
      /**
       * <code>optional string emitterAggregateId = 3;</code>
       */
      public boolean hasEmitterAggregateId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string emitterAggregateId = 3;</code>
       */
      public java.lang.String getEmitterAggregateId() {
        java.lang.Object ref = emitterAggregateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            emitterAggregateId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string emitterAggregateId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmitterAggregateIdBytes() {
        java.lang.Object ref = emitterAggregateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emitterAggregateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string emitterAggregateId = 3;</code>
       */
      public Builder setEmitterAggregateId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        emitterAggregateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string emitterAggregateId = 3;</code>
       */
      public Builder clearEmitterAggregateId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        emitterAggregateId_ = getDefaultInstance().getEmitterAggregateId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string emitterAggregateId = 3;</code>
       */
      public Builder setEmitterAggregateIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        emitterAggregateId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList customDestinationAggregateIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCustomDestinationAggregateIdsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          customDestinationAggregateIds_ = new com.google.protobuf.LazyStringArrayList(customDestinationAggregateIds_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string customDestinationAggregateIds = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getCustomDestinationAggregateIdsList() {
        return customDestinationAggregateIds_.getUnmodifiableView();
      }
      /**
       * <code>repeated string customDestinationAggregateIds = 4;</code>
       */
      public int getCustomDestinationAggregateIdsCount() {
        return customDestinationAggregateIds_.size();
      }
      /**
       * <code>repeated string customDestinationAggregateIds = 4;</code>
       */
      public java.lang.String getCustomDestinationAggregateIds(int index) {
        return customDestinationAggregateIds_.get(index);
      }
      /**
       * <code>repeated string customDestinationAggregateIds = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCustomDestinationAggregateIdsBytes(int index) {
        return customDestinationAggregateIds_.getByteString(index);
      }
      /**
       * <code>repeated string customDestinationAggregateIds = 4;</code>
       */
      public Builder setCustomDestinationAggregateIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomDestinationAggregateIdsIsMutable();
        customDestinationAggregateIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string customDestinationAggregateIds = 4;</code>
       */
      public Builder addCustomDestinationAggregateIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomDestinationAggregateIdsIsMutable();
        customDestinationAggregateIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string customDestinationAggregateIds = 4;</code>
       */
      public Builder addAllCustomDestinationAggregateIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureCustomDestinationAggregateIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, customDestinationAggregateIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string customDestinationAggregateIds = 4;</code>
       */
      public Builder clearCustomDestinationAggregateIds() {
        customDestinationAggregateIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string customDestinationAggregateIds = 4;</code>
       */
      public Builder addCustomDestinationAggregateIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomDestinationAggregateIdsIsMutable();
        customDestinationAggregateIds_.add(value);
        onChanged();
        return this;
      }

      private long systemTimestamp_ ;
      /**
       * <code>optional int64 systemTimestamp = 5;</code>
       */
      public boolean hasSystemTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 systemTimestamp = 5;</code>
       */
      public long getSystemTimestamp() {
        return systemTimestamp_;
      }
      /**
       * <code>optional int64 systemTimestamp = 5;</code>
       */
      public Builder setSystemTimestamp(long value) {
        bitField0_ |= 0x00000010;
        systemTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 systemTimestamp = 5;</code>
       */
      public Builder clearSystemTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        systemTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat vectorTimestamp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat, com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.Builder, com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormatOrBuilder> vectorTimestampBuilder_;
      /**
       * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
       */
      public boolean hasVectorTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat getVectorTimestamp() {
        if (vectorTimestampBuilder_ == null) {
          return vectorTimestamp_ == null ? com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.getDefaultInstance() : vectorTimestamp_;
        } else {
          return vectorTimestampBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
       */
      public Builder setVectorTimestamp(com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat value) {
        if (vectorTimestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vectorTimestamp_ = value;
          onChanged();
        } else {
          vectorTimestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
       */
      public Builder setVectorTimestamp(
          com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.Builder builderForValue) {
        if (vectorTimestampBuilder_ == null) {
          vectorTimestamp_ = builderForValue.build();
          onChanged();
        } else {
          vectorTimestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
       */
      public Builder mergeVectorTimestamp(com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat value) {
        if (vectorTimestampBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              vectorTimestamp_ != null &&
              vectorTimestamp_ != com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.getDefaultInstance()) {
            vectorTimestamp_ =
              com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.newBuilder(vectorTimestamp_).mergeFrom(value).buildPartial();
          } else {
            vectorTimestamp_ = value;
          }
          onChanged();
        } else {
          vectorTimestampBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
       */
      public Builder clearVectorTimestamp() {
        if (vectorTimestampBuilder_ == null) {
          vectorTimestamp_ = null;
          onChanged();
        } else {
          vectorTimestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.Builder getVectorTimestampBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getVectorTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormatOrBuilder getVectorTimestampOrBuilder() {
        if (vectorTimestampBuilder_ != null) {
          return vectorTimestampBuilder_.getMessageOrBuilder();
        } else {
          return vectorTimestamp_ == null ?
              com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.getDefaultInstance() : vectorTimestamp_;
        }
      }
      /**
       * <code>optional .VectorTimeFormat vectorTimestamp = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat, com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.Builder, com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormatOrBuilder> 
          getVectorTimestampFieldBuilder() {
        if (vectorTimestampBuilder_ == null) {
          vectorTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat, com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormat.Builder, com.rbmhtechnology.eventuate.serializer.CommonFormats.VectorTimeFormatOrBuilder>(
                  getVectorTimestamp(),
                  getParentForChildren(),
                  isClean());
          vectorTimestamp_ = null;
        }
        return vectorTimestampBuilder_;
      }

      private java.lang.Object processId_ = "";
      /**
       * <code>optional string processId = 7;</code>
       */
      public boolean hasProcessId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string processId = 7;</code>
       */
      public java.lang.String getProcessId() {
        java.lang.Object ref = processId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            processId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string processId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getProcessIdBytes() {
        java.lang.Object ref = processId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string processId = 7;</code>
       */
      public Builder setProcessId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        processId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string processId = 7;</code>
       */
      public Builder clearProcessId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        processId_ = getDefaultInstance().getProcessId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string processId = 7;</code>
       */
      public Builder setProcessIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        processId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object localLogId_ = "";
      /**
       * <code>optional string localLogId = 8;</code>
       */
      public boolean hasLocalLogId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string localLogId = 8;</code>
       */
      public java.lang.String getLocalLogId() {
        java.lang.Object ref = localLogId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            localLogId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string localLogId = 8;</code>
       */
      public com.google.protobuf.ByteString
          getLocalLogIdBytes() {
        java.lang.Object ref = localLogId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localLogId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string localLogId = 8;</code>
       */
      public Builder setLocalLogId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        localLogId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string localLogId = 8;</code>
       */
      public Builder clearLocalLogId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        localLogId_ = getDefaultInstance().getLocalLogId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string localLogId = 8;</code>
       */
      public Builder setLocalLogIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        localLogId_ = value;
        onChanged();
        return this;
      }

      private long localSequenceNr_ ;
      /**
       * <code>optional int64 localSequenceNr = 9;</code>
       */
      public boolean hasLocalSequenceNr() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 localSequenceNr = 9;</code>
       */
      public long getLocalSequenceNr() {
        return localSequenceNr_;
      }
      /**
       * <code>optional int64 localSequenceNr = 9;</code>
       */
      public Builder setLocalSequenceNr(long value) {
        bitField0_ |= 0x00000100;
        localSequenceNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 localSequenceNr = 9;</code>
       */
      public Builder clearLocalSequenceNr() {
        bitField0_ = (bitField0_ & ~0x00000100);
        localSequenceNr_ = 0L;
        onChanged();
        return this;
      }

      private long persistOnEventSequenceNr_ ;
      /**
       * <code>optional int64 persistOnEventSequenceNr = 10;</code>
       */
      public boolean hasPersistOnEventSequenceNr() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 persistOnEventSequenceNr = 10;</code>
       */
      public long getPersistOnEventSequenceNr() {
        return persistOnEventSequenceNr_;
      }
      /**
       * <code>optional int64 persistOnEventSequenceNr = 10;</code>
       */
      public Builder setPersistOnEventSequenceNr(long value) {
        bitField0_ |= 0x00000200;
        persistOnEventSequenceNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 persistOnEventSequenceNr = 10;</code>
       */
      public Builder clearPersistOnEventSequenceNr() {
        bitField0_ = (bitField0_ & ~0x00000200);
        persistOnEventSequenceNr_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object deliveryId_ = "";
      /**
       * <code>optional string deliveryId = 11;</code>
       */
      public boolean hasDeliveryId() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string deliveryId = 11;</code>
       */
      public java.lang.String getDeliveryId() {
        java.lang.Object ref = deliveryId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deliveryId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deliveryId = 11;</code>
       */
      public com.google.protobuf.ByteString
          getDeliveryIdBytes() {
        java.lang.Object ref = deliveryId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deliveryId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deliveryId = 11;</code>
       */
      public Builder setDeliveryId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        deliveryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deliveryId = 11;</code>
       */
      public Builder clearDeliveryId() {
        bitField0_ = (bitField0_ & ~0x00000400);
        deliveryId_ = getDefaultInstance().getDeliveryId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deliveryId = 11;</code>
       */
      public Builder setDeliveryIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        deliveryId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DurableEventFormat)
    }

    // @@protoc_insertion_point(class_scope:DurableEventFormat)
    private static final com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat();
    }

    public static com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DurableEventFormat>
        PARSER = new com.google.protobuf.AbstractParser<DurableEventFormat>() {
      public DurableEventFormat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DurableEventFormat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DurableEventFormat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DurableEventFormat> getParserForType() {
      return PARSER;
    }

    public com.rbmhtechnology.eventuate.serializer.DurableEventFormats.DurableEventFormat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DurableEventFormat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DurableEventFormat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031DurableEventFormats.proto\032\023CommonForma" +
      "ts.proto\"\306\002\n\022DurableEventFormat\022\037\n\007paylo" +
      "ad\030\001 \001(\0132\016.PayloadFormat\022\021\n\temitterId\030\002 " +
      "\001(\t\022\032\n\022emitterAggregateId\030\003 \001(\t\022%\n\035custo" +
      "mDestinationAggregateIds\030\004 \003(\t\022\027\n\017system" +
      "Timestamp\030\005 \001(\003\022*\n\017vectorTimestamp\030\006 \001(\013" +
      "2\021.VectorTimeFormat\022\021\n\tprocessId\030\007 \001(\t\022\022" +
      "\n\nlocalLogId\030\010 \001(\t\022\027\n\017localSequenceNr\030\t " +
      "\001(\003\022 \n\030persistOnEventSequenceNr\030\n \001(\003\022\022\n" +
      "\ndeliveryId\030\013 \001(\tB+\n\'com.rbmhtechnology.",
      "eventuate.serializerH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.rbmhtechnology.eventuate.serializer.CommonFormats.getDescriptor(),
        }, assigner);
    internal_static_DurableEventFormat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DurableEventFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DurableEventFormat_descriptor,
        new java.lang.String[] { "Payload", "EmitterId", "EmitterAggregateId", "CustomDestinationAggregateIds", "SystemTimestamp", "VectorTimestamp", "ProcessId", "LocalLogId", "LocalSequenceNr", "PersistOnEventSequenceNr", "DeliveryId", });
    com.rbmhtechnology.eventuate.serializer.CommonFormats.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
