/*
 * Copyright 2015 - 2016 Red Bull Media House GmbH <http://www.redbullmediahouse.com> - all rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReplicationFilterFormats.proto

package com.rbmhtechnology.eventuate.serializer;

public final class ReplicationFilterFormats {
  private ReplicationFilterFormats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReplicationFilterTreeFormatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReplicationFilterTreeFormat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ReplicationFilterTreeFormat.NodeType nodeType = 1;</code>
     */
    int getNodeTypeValue();
    /**
     * <code>.ReplicationFilterTreeFormat.NodeType nodeType = 1;</code>
     */
    com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType getNodeType();

    /**
     * <pre>
     * set if nodeType == LEAF
     * </pre>
     *
     * <code>.PayloadFormat filter = 2;</code>
     */
    boolean hasFilter();
    /**
     * <pre>
     * set if nodeType == LEAF
     * </pre>
     *
     * <code>.PayloadFormat filter = 2;</code>
     */
    com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat getFilter();
    /**
     * <pre>
     * set if nodeType == LEAF
     * </pre>
     *
     * <code>.PayloadFormat filter = 2;</code>
     */
    com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder getFilterOrBuilder();

    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    java.util.List<com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat> 
        getChildrenList();
    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat getChildren(int index);
    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    int getChildrenCount();
    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    java.util.List<? extends com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder> 
        getChildrenOrBuilderList();
    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder getChildrenOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ReplicationFilterTreeFormat}
   */
  public  static final class ReplicationFilterTreeFormat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReplicationFilterTreeFormat)
      ReplicationFilterTreeFormatOrBuilder {
    // Use ReplicationFilterTreeFormat.newBuilder() to construct.
    private ReplicationFilterTreeFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReplicationFilterTreeFormat() {
      nodeType_ = 0;
      children_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ReplicationFilterTreeFormat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              nodeType_ = rawValue;
              break;
            }
            case 18: {
              com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder subBuilder = null;
              if (filter_ != null) {
                subBuilder = filter_.toBuilder();
              }
              filter_ = input.readMessage(com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(filter_);
                filter_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                children_ = new java.util.ArrayList<com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat>();
                mutable_bitField0_ |= 0x00000004;
              }
              children_.add(
                  input.readMessage(com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          children_ = java.util.Collections.unmodifiableList(children_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_ReplicationFilterTreeFormat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_ReplicationFilterTreeFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.class, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder.class);
    }

    /**
     * Protobuf enum {@code ReplicationFilterTreeFormat.NodeType}
     */
    public enum NodeType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEAF = 0;</code>
       */
      LEAF(0),
      /**
       * <code>AND = 1;</code>
       */
      AND(1),
      /**
       * <code>OR = 2;</code>
       */
      OR(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>LEAF = 0;</code>
       */
      public static final int LEAF_VALUE = 0;
      /**
       * <code>AND = 1;</code>
       */
      public static final int AND_VALUE = 1;
      /**
       * <code>OR = 2;</code>
       */
      public static final int OR_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NodeType valueOf(int value) {
        return forNumber(value);
      }

      public static NodeType forNumber(int value) {
        switch (value) {
          case 0: return LEAF;
          case 1: return AND;
          case 2: return OR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NodeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NodeType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NodeType>() {
              public NodeType findValueByNumber(int number) {
                return NodeType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.getDescriptor().getEnumTypes().get(0);
      }

      private static final NodeType[] VALUES = values();

      public static NodeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NodeType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ReplicationFilterTreeFormat.NodeType)
    }

    private int bitField0_;
    public static final int NODETYPE_FIELD_NUMBER = 1;
    private int nodeType_;
    /**
     * <code>.ReplicationFilterTreeFormat.NodeType nodeType = 1;</code>
     */
    public int getNodeTypeValue() {
      return nodeType_;
    }
    /**
     * <code>.ReplicationFilterTreeFormat.NodeType nodeType = 1;</code>
     */
    public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType getNodeType() {
      com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType result = com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType.valueOf(nodeType_);
      return result == null ? com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType.UNRECOGNIZED : result;
    }

    public static final int FILTER_FIELD_NUMBER = 2;
    private com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat filter_;
    /**
     * <pre>
     * set if nodeType == LEAF
     * </pre>
     *
     * <code>.PayloadFormat filter = 2;</code>
     */
    public boolean hasFilter() {
      return filter_ != null;
    }
    /**
     * <pre>
     * set if nodeType == LEAF
     * </pre>
     *
     * <code>.PayloadFormat filter = 2;</code>
     */
    public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat getFilter() {
      return filter_ == null ? com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.getDefaultInstance() : filter_;
    }
    /**
     * <pre>
     * set if nodeType == LEAF
     * </pre>
     *
     * <code>.PayloadFormat filter = 2;</code>
     */
    public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder getFilterOrBuilder() {
      return getFilter();
    }

    public static final int CHILDREN_FIELD_NUMBER = 3;
    private java.util.List<com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat> children_;
    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    public java.util.List<com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat> getChildrenList() {
      return children_;
    }
    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    public java.util.List<? extends com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder> 
        getChildrenOrBuilderList() {
      return children_;
    }
    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <pre>
     * set if nodeType == AND | OR
     * </pre>
     *
     * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
     */
    public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder getChildrenOrBuilder(
        int index) {
      return children_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nodeType_ != com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType.LEAF.getNumber()) {
        output.writeEnum(1, nodeType_);
      }
      if (filter_ != null) {
        output.writeMessage(2, getFilter());
      }
      for (int i = 0; i < children_.size(); i++) {
        output.writeMessage(3, children_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nodeType_ != com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType.LEAF.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, nodeType_);
      }
      if (filter_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFilter());
      }
      for (int i = 0; i < children_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, children_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat)) {
        return super.equals(obj);
      }
      com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat other = (com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat) obj;

      boolean result = true;
      result = result && nodeType_ == other.nodeType_;
      result = result && (hasFilter() == other.hasFilter());
      if (hasFilter()) {
        result = result && getFilter()
            .equals(other.getFilter());
      }
      result = result && getChildrenList()
          .equals(other.getChildrenList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODETYPE_FIELD_NUMBER;
      hash = (53 * hash) + nodeType_;
      if (hasFilter()) {
        hash = (37 * hash) + FILTER_FIELD_NUMBER;
        hash = (53 * hash) + getFilter().hashCode();
      }
      if (getChildrenCount() > 0) {
        hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
        hash = (53 * hash) + getChildrenList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReplicationFilterTreeFormat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReplicationFilterTreeFormat)
        com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_ReplicationFilterTreeFormat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_ReplicationFilterTreeFormat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.class, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder.class);
      }

      // Construct using com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChildrenFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        nodeType_ = 0;

        if (filterBuilder_ == null) {
          filter_ = null;
        } else {
          filter_ = null;
          filterBuilder_ = null;
        }
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_ReplicationFilterTreeFormat_descriptor;
      }

      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat getDefaultInstanceForType() {
        return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.getDefaultInstance();
      }

      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat build() {
        com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat buildPartial() {
        com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat result = new com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.nodeType_ = nodeType_;
        if (filterBuilder_ == null) {
          result.filter_ = filter_;
        } else {
          result.filter_ = filterBuilder_.build();
        }
        if (childrenBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            children_ = java.util.Collections.unmodifiableList(children_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.children_ = children_;
        } else {
          result.children_ = childrenBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat) {
          return mergeFrom((com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat other) {
        if (other == com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.getDefaultInstance()) return this;
        if (other.nodeType_ != 0) {
          setNodeTypeValue(other.getNodeTypeValue());
        }
        if (other.hasFilter()) {
          mergeFilter(other.getFilter());
        }
        if (childrenBuilder_ == null) {
          if (!other.children_.isEmpty()) {
            if (children_.isEmpty()) {
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureChildrenIsMutable();
              children_.addAll(other.children_);
            }
            onChanged();
          }
        } else {
          if (!other.children_.isEmpty()) {
            if (childrenBuilder_.isEmpty()) {
              childrenBuilder_.dispose();
              childrenBuilder_ = null;
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000004);
              childrenBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChildrenFieldBuilder() : null;
            } else {
              childrenBuilder_.addAllMessages(other.children_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int nodeType_ = 0;
      /**
       * <code>.ReplicationFilterTreeFormat.NodeType nodeType = 1;</code>
       */
      public int getNodeTypeValue() {
        return nodeType_;
      }
      /**
       * <code>.ReplicationFilterTreeFormat.NodeType nodeType = 1;</code>
       */
      public Builder setNodeTypeValue(int value) {
        nodeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ReplicationFilterTreeFormat.NodeType nodeType = 1;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType getNodeType() {
        com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType result = com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType.valueOf(nodeType_);
        return result == null ? com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ReplicationFilterTreeFormat.NodeType nodeType = 1;</code>
       */
      public Builder setNodeType(com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.NodeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        nodeType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ReplicationFilterTreeFormat.NodeType nodeType = 1;</code>
       */
      public Builder clearNodeType() {
        
        nodeType_ = 0;
        onChanged();
        return this;
      }

      private com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat filter_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder> filterBuilder_;
      /**
       * <pre>
       * set if nodeType == LEAF
       * </pre>
       *
       * <code>.PayloadFormat filter = 2;</code>
       */
      public boolean hasFilter() {
        return filterBuilder_ != null || filter_ != null;
      }
      /**
       * <pre>
       * set if nodeType == LEAF
       * </pre>
       *
       * <code>.PayloadFormat filter = 2;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat getFilter() {
        if (filterBuilder_ == null) {
          return filter_ == null ? com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.getDefaultInstance() : filter_;
        } else {
          return filterBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * set if nodeType == LEAF
       * </pre>
       *
       * <code>.PayloadFormat filter = 2;</code>
       */
      public Builder setFilter(com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat value) {
        if (filterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          filter_ = value;
          onChanged();
        } else {
          filterBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * set if nodeType == LEAF
       * </pre>
       *
       * <code>.PayloadFormat filter = 2;</code>
       */
      public Builder setFilter(
          com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder builderForValue) {
        if (filterBuilder_ == null) {
          filter_ = builderForValue.build();
          onChanged();
        } else {
          filterBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * set if nodeType == LEAF
       * </pre>
       *
       * <code>.PayloadFormat filter = 2;</code>
       */
      public Builder mergeFilter(com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat value) {
        if (filterBuilder_ == null) {
          if (filter_ != null) {
            filter_ =
              com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.newBuilder(filter_).mergeFrom(value).buildPartial();
          } else {
            filter_ = value;
          }
          onChanged();
        } else {
          filterBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * set if nodeType == LEAF
       * </pre>
       *
       * <code>.PayloadFormat filter = 2;</code>
       */
      public Builder clearFilter() {
        if (filterBuilder_ == null) {
          filter_ = null;
          onChanged();
        } else {
          filter_ = null;
          filterBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * set if nodeType == LEAF
       * </pre>
       *
       * <code>.PayloadFormat filter = 2;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder getFilterBuilder() {
        
        onChanged();
        return getFilterFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * set if nodeType == LEAF
       * </pre>
       *
       * <code>.PayloadFormat filter = 2;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder getFilterOrBuilder() {
        if (filterBuilder_ != null) {
          return filterBuilder_.getMessageOrBuilder();
        } else {
          return filter_ == null ?
              com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.getDefaultInstance() : filter_;
        }
      }
      /**
       * <pre>
       * set if nodeType == LEAF
       * </pre>
       *
       * <code>.PayloadFormat filter = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder> 
          getFilterFieldBuilder() {
        if (filterBuilder_ == null) {
          filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormat.Builder, com.rbmhtechnology.eventuate.serializer.CommonFormats.PayloadFormatOrBuilder>(
                  getFilter(),
                  getParentForChildren(),
                  isClean());
          filter_ = null;
        }
        return filterBuilder_;
      }

      private java.util.List<com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat> children_ =
        java.util.Collections.emptyList();
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          children_ = new java.util.ArrayList<com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat>(children_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder> childrenBuilder_;

      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public java.util.List<com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat> getChildrenList() {
        if (childrenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(children_);
        } else {
          return childrenBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public int getChildrenCount() {
        if (childrenBuilder_ == null) {
          return children_.size();
        } else {
          return childrenBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat getChildren(int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);
        } else {
          return childrenBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public Builder setChildren(
          int index, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.set(index, value);
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public Builder setChildren(
          int index, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.set(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public Builder addChildren(com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public Builder addChildren(
          int index, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(index, value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public Builder addChildren(
          com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public Builder addChildren(
          int index, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public Builder addAllChildren(
          java.lang.Iterable<? extends com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat> values) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, children_);
          onChanged();
        } else {
          childrenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public Builder clearChildren() {
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public Builder removeChildren(int index) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.remove(index);
          onChanged();
        } else {
          childrenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder getChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder getChildrenOrBuilder(
          int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);  } else {
          return childrenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public java.util.List<? extends com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder> 
           getChildrenOrBuilderList() {
        if (childrenBuilder_ != null) {
          return childrenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(children_);
        }
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder addChildrenBuilder() {
        return getChildrenFieldBuilder().addBuilder(
            com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.getDefaultInstance());
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder addChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().addBuilder(
            index, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.getDefaultInstance());
      }
      /**
       * <pre>
       * set if nodeType == AND | OR
       * </pre>
       *
       * <code>repeated .ReplicationFilterTreeFormat children = 3;</code>
       */
      public java.util.List<com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder> 
           getChildrenBuilderList() {
        return getChildrenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder> 
          getChildrenFieldBuilder() {
        if (childrenBuilder_ == null) {
          childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat.Builder, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormatOrBuilder>(
                  children_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          children_ = null;
        }
        return childrenBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ReplicationFilterTreeFormat)
    }

    // @@protoc_insertion_point(class_scope:ReplicationFilterTreeFormat)
    private static final com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat();
    }

    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReplicationFilterTreeFormat>
        PARSER = new com.google.protobuf.AbstractParser<ReplicationFilterTreeFormat>() {
      public ReplicationFilterTreeFormat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReplicationFilterTreeFormat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReplicationFilterTreeFormat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReplicationFilterTreeFormat> getParserForType() {
      return PARSER;
    }

    public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.ReplicationFilterTreeFormat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NoFilterFormatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NoFilterFormat)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * no fields
   * </pre>
   *
   * Protobuf type {@code NoFilterFormat}
   */
  public  static final class NoFilterFormat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NoFilterFormat)
      NoFilterFormatOrBuilder {
    // Use NoFilterFormat.newBuilder() to construct.
    private NoFilterFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NoFilterFormat() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NoFilterFormat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_NoFilterFormat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_NoFilterFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat.class, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat)) {
        return super.equals(obj);
      }
      com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat other = (com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * no fields
     * </pre>
     *
     * Protobuf type {@code NoFilterFormat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NoFilterFormat)
        com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_NoFilterFormat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_NoFilterFormat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat.class, com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat.Builder.class);
      }

      // Construct using com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.internal_static_NoFilterFormat_descriptor;
      }

      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat getDefaultInstanceForType() {
        return com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat.getDefaultInstance();
      }

      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat build() {
        com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat buildPartial() {
        com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat result = new com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat) {
          return mergeFrom((com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat other) {
        if (other == com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:NoFilterFormat)
    }

    // @@protoc_insertion_point(class_scope:NoFilterFormat)
    private static final com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat();
    }

    public static com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NoFilterFormat>
        PARSER = new com.google.protobuf.AbstractParser<NoFilterFormat>() {
      public NoFilterFormat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NoFilterFormat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NoFilterFormat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NoFilterFormat> getParserForType() {
      return PARSER;
    }

    public com.rbmhtechnology.eventuate.serializer.ReplicationFilterFormats.NoFilterFormat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReplicationFilterTreeFormat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReplicationFilterTreeFormat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NoFilterFormat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NoFilterFormat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036ReplicationFilterFormats.proto\032\023Common" +
      "Formats.proto\"\315\001\n\033ReplicationFilterTreeF" +
      "ormat\0227\n\010nodeType\030\001 \001(\0162%.ReplicationFil" +
      "terTreeFormat.NodeType\022\036\n\006filter\030\002 \001(\0132\016" +
      ".PayloadFormat\022.\n\010children\030\003 \003(\0132\034.Repli" +
      "cationFilterTreeFormat\"%\n\010NodeType\022\010\n\004LE" +
      "AF\020\000\022\007\n\003AND\020\001\022\006\n\002OR\020\002\"\020\n\016NoFilterFormatB" +
      "+\n\'com.rbmhtechnology.eventuate.serializ" +
      "erH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.rbmhtechnology.eventuate.serializer.CommonFormats.getDescriptor(),
        }, assigner);
    internal_static_ReplicationFilterTreeFormat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReplicationFilterTreeFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReplicationFilterTreeFormat_descriptor,
        new java.lang.String[] { "NodeType", "Filter", "Children", });
    internal_static_NoFilterFormat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NoFilterFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NoFilterFormat_descriptor,
        new java.lang.String[] { });
    com.rbmhtechnology.eventuate.serializer.CommonFormats.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
